Repository orange-cloudavenue/cloudavenue-sdk-go-v2, pull requests merged in 2025-08, with the labels that each got.

#61 feat: Add List Storage Profile query
  api/vdc/v1/storage_profile_commands.go
  api/vdc/v1/storage_profile_test.go
  api/vdc/v1/vdc_commands.go
  api/vdc/v1/vdc_rules.go
  api/vdc/v1/vdc_test.go
  api/vdc/v1/zz_storage_profile.go
  api/vdc/v1/zz_vdc.go
  api/vdcgroup/v1/zz_vdcgroup.go
  cmd/devref/go.mod
  cmd/devref/go.sum
  cmd/endpoint-dev/command.go
  cmd/endpoint-dev/go.mod
  cmd/endpoint-dev/go.sum
  cmd/endpoint-dev/root.go
  endpoints/zz_storage_profile.go
  internal/iendpoints/storage_profile.go
  internal/itypes/vdc_storage_profile.go
  types/vdc.go
  types/vdc_storage_profile.go
Labels: feature, size/L

#68 fix: retry if already exist
  cav/client_request.go
  cav/jobs.go
  cav/subclient_cerberus.go
  cav/subclient_cerberus_jobs.go
Labels: fix, size/S

#72 chore: devtool command multi namespace + config in keystore
  cav/client_options.go
  cmd/devtool/client.go
  cmd/devtool/command.go
  cmd/devtool/command_help.go
  cmd/devtool/config.go
  cmd/devtool/endpoint.go
  cmd/devtool/go.mod
  cmd/devtool/go.sum
  cmd/devtool/help.go
  cmd/devtool/import.go
  cmd/devtool/main.go
  cmd/devtool/root.go
  cmd/devtool/spin.go
  cmd/endpoint-dev/config.go
  internal/httpClient/client.go
Labels: chore, size/M, sdkv2

#71 chore: add new command http
  cav/client_request.go
  cmd/devtool/http-client.go
Labels: chore, size/S

#75 fix: edgegateway api
  api/edgegateway/v1/bandwidth_commands.go
  api/edgegateway/v1/edgegateway_commands.go
  api/edgegateway/v1/edgegateway_test.go
  api/edgegateway/v1/zz_bandwidth.go
  api/edgegateway/v1/zz_edgegateway.go
  api/edgegateway/v1/zz_publicip.go
  api/edgegateway/v1/zz_services.go
  api/edgegateway/v1/zz_t0.go
  cav/endpoint_registry.go
  cav/endpoint_response_mock.go
  cav/subclient.go
  cav/subclient_cerberus.go
  cav/subclient_vmware.go
  cmd/devtool/go.mod
  cmd/devtool/go.sum
  go.mod
  go.sum
  internal/iendpoints/edgegateway.go
  types/edgegateway.go
Labels: fix, size/M
